### ISSUE TITLE
When I execute the step "python setup.py build develop", it gives an error saying that python>=3.8 is required, but your requirement is python=3.7 when creating the environment. So what  should I do？

### ISSUE THREAD

**Issue by wha-cloud** [CityU-AIM-Group/SIGMA#1]
When I execute the step "python setup.py build develop", it gives an error saying that python>=3.8 is required, but your requirement is python=3.7 when creating the environment. So what  should I do？

**Comment by wymanCV** [comment]
Hi, could you please show me your conda and pip environments?

I just tried to install it on my local computer and didn't meet such a problem. 

My conda env: cudatoolkit: 10.0 (I used 10.1 and 11.1 on my servers)
My python version: 3.7.9
My pip env:
torch 1.4.0
torchvision: 0.2.1

**Comment by wha-cloud** [comment]
我在创建环境是吧python版本改成3.8就可以了

**Comment by wymanCV** [comment]
> 我这边遇到了一样的问题，log如下。 推测是自动安装了过于新的 scipy，手动安装要求的 scipy1.4.1 后，重新运行 setup.py 就可以完成安装了。
> 
> > Searching for scipy>=1.4.1
> > Reading https://pypi.org/simple/scipy/
> > Downloading https://files.pythonhosted.org/packages/b4/a2/4faa34bf0cdbefd5c706625f1234987795f368eb4e97bde9d6f46860843e/scipy-1.8.0.tar.gz#sha256=31d4f2d6b724bc9a98e527b5849b8a7e589bf1ea630c33aa563eda912c9ff0bd
> > Best match: scipy 1.8.0
> > Processing scipy-1.8.0.tar.gz
> > Writing /tmp/easy_install-ssmdbg_7/scipy-1.8.0/setup.cfg
> > Running scipy-1.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ssmdbg_7/scipy-1.8.0/egg-dist-tmp-my8lqpcn
> > Traceback (most recent call last):
> > File "/home/sipl/miniconda3/envs/SIGMA/lib/python3.7/site-packages/setuptools/sandbox.py", line 156, in save_modules
> > yield saved
> > File "/home/sipl/miniconda3/envs/SIGMA/lib/python3.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
> > yield
> > File "/home/sipl/miniconda3/envs/SIGMA/lib/python3.7/site-packages/setuptools/sandbox.py", line 259, in run_setup
> > _execfile(setup_script, ns)
> > File "/home/sipl/miniconda3/envs/SIGMA/lib/python3.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
> > exec(code, globals, locals)
> > File "/tmp/easy_install-ssmdbg_7/scipy-1.8.0/setup.py", line 31, in 
> > source_cpu = glob.glob(os.path.join(extensions_dir, "cpu", "*.cpp"))
> > RuntimeError: Python version >= 3.8 required.
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "setup.py", line 77, in 
> > include_package_data=True,
> > File "/home/sipl/miniconda3/envs/SIGMA/lib/python3.7/site-packages/setuptools/**init**.py", line 87, in setup
> > return distutils.core.setup(**attrs)
> > ...
> > File "/tmp/easy_install-ssmdbg_7/scipy-1.8.0/setup.py", line 31, in 
> > source_cpu = glob.glob(os.path.join(extensions_dir, "cpu", "*.cpp"))
> > RuntimeError: Python version >= 3.8 required.

感谢回复，我刚刚查看了我的scipy版本是1.6, 的确可能是自动安装的1.8版本过高的原因
