### ISSUE TITLE
有关实验结果的一些疑问

### ISSUE THREAD

**Issue by wokeyide1999** [CityU-AIM-Group/SIGMA#12]
您好，我在原实验参数未做更改的情况下完成了阶段性实验，下面我先对本人的实验过程做一下说明：
1、实验环境配置中我使用的高版本cuda
2、整个实验过程存在两次中断，第一次迭代了15200次，中断原因不明，在6200次自动保存了最高结果49.2；第二次迭代了21440次，中断原因为“OSError: [Errno 28] No space left on device”，在10400次自动保存了最高结果51.39；第三次迭代了30000次，无中断，在23800次自动保存了最高结果54.76。后两次训练均为接续训练，不是从头开始。

问题：
1、为什么自动保存的是效果最好的模型结果，而非是按迭代次数保存，比如每10000次迭代保存一个pth

2、github所给代码是Conference verison吗？

3、三次实验总共60000次迭代的结果是54.76，结果是否合理？若要达到57.1是否只能继续训练？

4、若我要做消融对比实验，仅对比实验结果来判断哪些模块更为有效，那么多少次迭代比较合适，或者说该如何进行比较，因为完整的100000次迭代耗时太久了

三次实验日志如下：
第一次：
[train111.log](https://github.com/CityU-AIM-Group/SIGMA/files/9131118/train111.log)

第二次：
[train112.log](https://github.com/CityU-AIM-Group/SIGMA/files/9131119/train112.log)

第三次：
[train113.log](https://github.com/CityU-AIM-Group/SIGMA/files/9131120/train113.log)

最后的测试结果：
![1](https://user-images.githubusercontent.com/50702089/179490724-fcdce4db-b7f8-4303-a5c7-efc171c6e6ef.png)

![2](https://user-images.githubusercontent.com/50702089/179490743-29601b71-0f93-46b3-a96e-dd1c6c3700e1.png)

**Comment by wymanCV** [comment]
您好，感谢你对本工作的关注。
1）不知道你是否熟悉其他DAOD框架，由于对抗训练的不稳定性，目前几乎所有的DAOD算法的benchmark结果都是通过不公开的model selection得到的，这导致我曾经很难直接复现他们论文的结果。所以，在本工作里，与其存海量模型进行进一步model selection，不如直接让follower能直接跑出我们的结果，（我曾经花了将近一个月时间才跑出我们的baseline的论文类似结果，貌似你一次就跑出了我们差不多的结果了），而且这个做法在UDA里是基操。
2） 是的。 
3）合理，你跑的应该是sim2city吧，你可以发现我们论文里汇报的是53左右，你跑出来54.7已经超过所有sota了，我们的57.1是通过详细调参以及多阶段才得到的，我们端到端训练也只能达到55左右的结果，DAOD算法非常难调且不稳定。 
4） 你可以调整trainer.py里面的模型保存策略，并且自行尝试不同的迭代数（6w迭代对于DAOD真的很少，有的DAOD工作跑几十万iter寻找benchmark结果），而且由于对抗训练的不稳定性，也很难保证一次设置就合适，我们也是跑了上百个实验。
对于SIGMA的潜力能到哪，其实我们也很难说，因为我们的研究程度也有限（很多时候一个参数设置偏差就会导致性能下降），不过目前来看您已经能复现出高于我们论文汇报的结果了~

**Comment by wokeyide1999** [comment]
明白了！感谢您的解答！
