### ISSUE TITLE
multi gpu training

### ISSUE THREAD

**Issue by yaojunr** [CityU-AIM-Group/SIGMA#14]
Hello, thanks for you work.
I notice there is no command in your README for multi gpu training. I use the following command to train.
`python tools/train_net_da.py --confpython -m torch.distributed.launch --nproc_per_node 4 tools/train_net_da.py --config-file configs/SIGMA/sigma_vgg16_sim10k_to_cityscapes.yamlig-file configs/SIGMA/sigma_vgg16_sim10k_to_cityscapes.yaml`
However, I meet a problem
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. 
You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. 
Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
```
How can I solve this problem to train on multiple gpus?

**Comment by wymanCV** [comment]
Hi, thank you for your attention to our work.

I am sorry that our framework doesn't support the distributed training now. Kindly use one GPU for training, which won't take much time to achieve comparable results.

**Comment by wymanCV** [comment]
Thank you for your interest in our work. Feel free to reopen the issue if you have follow-up questions, or contact me by email.
