### ISSUE TITLE
Hi, thank you for your good job! However, can you tell me what GPU you use to train the model? 

### ISSUE THREAD

**Issue by ga546** [CityU-AIM-Group/SIGMA#16]

**Comment by wymanCV** [comment]
Hi, thanks for your interests on our work.

I tried V100 (bs=4) and 2080Ti (bs=2), and they were both ok. If you use 3090 with cuda11, it needs to fix some small compiling errors during runing setup.py.

**Comment by ga546** [comment]
thanks for your reply! I got it @wymanCV
