### ISSUE TITLE
target = target.resize(image.size)  AttributeError: 'list' object has no attribute 'resize'

### ISSUE THREAD

**Issue by sysuzgg** [CityU-AIM-Group/SIGMA#17]
fcos_core/data/transforms/transforms.py line 61, in __call__  report "AttributeError: 'list' object has no attribute 'resize'". When I change it to "target = F.resize(target, size),  it reported " TypeError: img should be PIL Image. Got <class 'list'>" . Can you help me?

**Comment by sysuzgg** [comment]
I found that this error may be related to the version of torchvision. what is your version of torchvision

**Comment by wymanCV** [comment]
Hi, we use torchvision == 0.21, as illustrated in [INSTALL](https://github.com/CityU-AIM-Group/SIGMA/blob/main/INSTALL.md).  The published code should be able to run directly without other modifications.

**Comment by sysuzgg** [comment]
Thanks a lot! Installing the version as illustrated in INSTALL, there is no problem.

> 

> Hi, we use torchvision == 0.21, as illustrated in [INSTALL](https://github.com/CityU-AIM-Group/SIGMA/blob/main/INSTALL.md). The published code should be able to run directly without other modifications.
