### ISSUE TITLE
训练source-only

### ISSUE THREAD

**Issue by sysuzgg** [CityU-AIM-Group/SIGMA#18]
如果要训练source-only的结果（单纯训练FCOS），是用tools/train_net.py, 以及yaml文件的FCOS_ON： False训练吗？ 还是tools/train_net_da.py, FCOS_ON： False 即可呢？

**Comment by wymanCV** [comment]
理论上设置DA_ON False就可以，因为这个仓库是基于Every pixel matter 修改的，原仓库预留了这个接口，可以看这个 [issue](https://github.com/chengchunhsu/EveryPixelMatters/issues/1#issuecomment-684061201) 。不过我们没有复现过source-only的实验，如果遇到bug可以考虑直接用不含有DA的FCOS框架。

**Comment by sysuzgg** [comment]
> 理论上设置DA_ON False就可以，因为这个仓库是基于Every pixel matter 修改的，原仓库预留了这个接口，可以看这个 [issue](https://github.com/chengchunhsu/EveryPixelMatters/issues/1#issuecomment-684061201) 。不过我们没有复现过source-only的实验，如果遇到bug可以考虑直接用不含有DA的FCOS框架。

好的，非常感谢！
