### ISSUE TITLE
下载sim10k数据集

### ISSUE THREAD

**Issue by O2andsAnoxia** [CityU-AIM-Group/SIGMA#19]
你好，请问能分享下sim10k数据集么，官网上下载不了了，如果不方便贴网盘链接，这是我的邮箱1766529899@qq.com

**Comment by O2andsAnoxia** [comment]
十分感谢

**Comment by wymanCV** [comment]
您好，感谢您对本工作的关注。

我在百度网盘上传了sim10k数据集：

链接: https://pan.baidu.com/s/1rsCsMIj7hi1Hd59_icv_qQ 提取码: duut

**Comment by wymanCV** [comment]
感谢您对我们工作的关注，如果有后续问题欢迎重新打开问题，或者通过电子邮件联系我。

**Comment by Re-dot-art** [comment]
> 您好，感谢您对本工作的关注。
> 
> 我在百度网盘上传了sim10k数据集：
> 
> 链接: https://pan.baidu.com/s/1rsCsMIj7hi1Hd59_icv_qQ 提取码: duut

您好，我下载了您分享的网盘数据集，我发现在ImageSets中的文件好像没有val.txt，请问这种是正常的吗？还是需要自己划分？
![image](https://github.com/CityU-AIM-Group/SIGMA/assets/93500522/a8b653de-b53c-41ee-b0a5-ef22ec34cef4)
谢谢！

**Comment by wymanCV** [comment]
> > 您好，感谢您对本工作的关注。
> > 我在百度网盘上传了sim10k数据集：
> > 链接: https://pan.baidu.com/s/1rsCsMIj7hi1Hd59_icv_qQ 提取码: duut
> 
> 您好，我下载了您分享的网盘数据集，我发现在ImageSets中的文件好像没有val.txt，请问这种是正常的吗？还是需要自己划分？ ![image](https://private-user-images.githubusercontent.com/93500522/332257946-a8b653de-b53c-41ee-b0a5-ef22ec34cef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjM5NzEsIm5iZiI6MTcxNjI2MzY3MSwicGF0aCI6Ii85MzUwMDUyMi8zMzIyNTc5NDYtYThiNjUzZGUtYjUzYy00MWVlLWIwYTUtZWYyMmVjMzRjZWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAzNTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZmI3OWM4NGQzYWUxZjllMmZmNGM5Zjk2MmYyZGJjNmYwYmM3M2IyNzQ1OGNjZDZjZjc4NWYyNzA5NTQwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XGBoWph8EM1xnC9rnCQl2v5CfQgs3RF9bsacjh5U2-0) 谢谢！

您好，benchmark设定中Sim10k只用于源域的训练，测试的时候是在目标域Cityscapes val上测试，所以不需要划分。
