### ISSUE TITLE
Hello, When I tried to test using the pretrained weight i got the following error.please help

### ISSUE THREAD

**Issue by AstuWeb** [CityU-AIM-Group/SIGMA#2]
![Screenshot from 2022-05-04 01-51-36](https://user-images.githubusercontent.com/50729468/166629050-2023c9cc-9bf0-411a-b7b3-b1532e2e633c.png)

**Comment by wymanCV** [comment]
Sorry for the typo error. Kindly change the commend "WEIGHT" into "MODEL.WEIGHT", which will rewrite the model dir in "https://github.com/CityU-AIM-Group/SIGMA/blob/main/configs/SIGMA/sigma_vgg16_cityscapace_to_foggy.yaml". BTW, please do not use the final model to evaluate since we set maxiter large enough to train enough time.

**Comment by AstuWeb** [comment]
Okay thank you for the quick reply. this time it works but it shows low result than expected. here i attach  the screenshot.
![Screenshot from 2022-05-04 02-08-43](https://user-images.githubusercontent.com/50729468/166630653-908cce56-0c8c-4f07-9fec-7cf5f08f905b.png)

**Comment by wymanCV** [comment]
Hi, could you please show me some internal validation results (around 10000 iterations)? I remember the res50 could achieve the best result around 20000 iterations.
 We have rerun SIGMA end-to-end with VGG-16 backbone for C2F and S2F, which gives 43.5 and 55.0 mAP. I will check about the res50 backbone.

**Comment by AstuWeb** [comment]
Oh I didn't train it yet I just use the pretrained model you provided to see the results. these results are from the pretrained model 'city_to_foggy_res50_44.26_mAP.pth'

**Comment by wymanCV** [comment]
> Oh I didn't train it yet I just use the pretrained model you provided to see the results. these results are from the pretrained model 'city_to_foggy_res50_44.26_mAP.pth'

Hi, I just tested with our pre-trained model and didn't find such a problem:
pls use the commend to test : 
python tools/test_net.py --config-file configs/SIGMA/sigma_res50_cityscapace_to_foggy.yaml MODEL.WEIGHT city_to_foggy_res50_44.26_mAP.pth

![image](https://user-images.githubusercontent.com/93365573/166632631-17aea877-7034-4306-abe9-4bc72eda1c09.png)

**Comment by AstuWeb** [comment]
Okay I see . Thankyou for the detailed explanation. I check again but same results. I appreciate if you can point out some possible reasons that may cause this issue. for me everything seems fine.

**Comment by wymanCV** [comment]
This framework will automatically load the last checkpoint. Check if our well-trained model is loaded correctly, I noticed that you seem to load "models/ model_fianl.pth" instead of our well-trained model
![image](https://user-images.githubusercontent.com/93365573/166637864-2c37a69e-3941-47d4-bc43-60428b88daf8.png)

**Comment by AstuWeb** [comment]
Here is the test log. kindly please find it on the provided link.
https://github.com/AstuWeb/CrudPHP/blob/master/test_log.txt

**Comment by wymanCV** [comment]
It is very interesting that the performance of the class rider is the same: 0.493, which makes me very confused.  Do your prepare your dataset correctly as [EPM](https://github.com/chengchunhsu/EveryPixelMatters  ) ? Have you tried other models, e.g., VGG-16 ?

Actually,  I just cloned this project again, redownloaded the annotation cityscapes_foggy_val_cocostyle.json,  evaluated it, and still couldn't get your results...

**Comment by wymanCV** [comment]
> Here is the test log. kindly please find it on the provided link. https://github.com/AstuWeb/CrudPHP/blob/master/test_log.txt

This is the automatically generated detection results file, could your please share yours?
[cityscapes_foggy_val_cocostyle.zip](https://github.com/CityU-AIM-Group/SIGMA/files/8618861/cityscapes_foggy_val_cocostyle.zip)

This is the annotation file from EPM, which is the same as us.
[cityscapes_foggy_val_cocostyle.zip](https://github.com/CityU-AIM-Group/SIGMA/files/8618869/cityscapes_foggy_val_cocostyle.zip)

**Comment by AstuWeb** [comment]
Sure Here is the auto generated Detection results  https://github.com/AstuWeb/Test/blob/main/cityscapes_foggy_val_cocostyle.zip

**Comment by AstuWeb** [comment]
and this is the json annotation I uses [https://github.com/AstuWeb/Test/blob/main/foggy_instancesonly_filtered_gtFine_val.zip](url)

**Comment by wymanCV** [comment]
> and this is the json annotation I uses https://github.com/AstuWeb/Test/blob/main/foggy_instancesonly_filtered_gtFine_val.zip


LOL, just like what I have expected! The encoded class number is different between your and our annotations! PLS be carefully to use this annotation file [THIS](https://drive.google.com/file/d/1LRNXW2Wee8tjuxc5gjVsFQv49vA_SBtk/view)

![image](https://user-images.githubusercontent.com/93365573/166660713-6f8eea85-bb13-42cb-9742-2d6847bea0f6.png)

**Comment by wymanCV** [comment]
and this is the json annotation I uses https://github.com/AstuWeb/Test/blob/main/foggy_instancesonly_filtered_gtFine_val.zip

LOL, just like what I have expected! The encoded class number is different between your and our annotations! PLS be carefully to use this annotation file [THIS](https://drive.google.com/file/d/1LRNXW2Wee8tjuxc5gjVsFQv49vA_SBtk/view)

![image](https://user-images.githubusercontent.com/93365573/166661153-2ba64d51-ecf5-4135-af1f-a96e60763aca.png)

**Comment by AstuWeb** [comment]
Thank you so much. Now i get these good results. You are so helpful.
![new](https://user-images.githubusercontent.com/50729468/166663584-6ce9c2b1-fcf2-43a7-b255-1d522cbdd058.png)

**Comment by wymanCV** [comment]
> Thank you so much. Now i get these good results. You are so helpful. ![new](https://user-images.githubusercontent.com/50729468/166663584-6ce9c2b1-fcf2-43a7-b255-1d522cbdd058.png)

You're welcome, and please close this issue. If your think this work is helpful for your project, kindly give it a star and citation. Thanks

**Comment by AstuWeb** [comment]
Yes sure thanks I will create another if I encountered issue during the training .
