### ISSUE TITLE
作者你好！我想请问一下训练各个模型的时间是多少？

### ISSUE THREAD

**Issue by PungTeng** [CityU-AIM-Group/SIGMA#20]

**Comment by wymanCV** [comment]
您好，感谢您的关注。city2foggy 和 sim2city 单卡跑大概一天左右就行，kitti2city 不到半天。

**Comment by PungTeng** [comment]
> 

感谢作者回答，我测试resnet50 city2foggy在单卡3090上面，显示要两天多，请问这是什么原因呢?

<img width="421" alt="image" src="https://user-images.githubusercontent.com/48271804/202218373-889619a1-cdd9-4791-86dc-81b256dfeabb.png">

<img width="688" alt="image" src="https://user-images.githubusercontent.com/48271804/202218494-278862c5-6487-4894-a4f9-e7e1ce9c01bf.png">

@wymanCV

**Comment by wymanCV** [comment]
你好，那个训练迭代时间实际不需要那么长，我们设置的稍微长一些是为了更容易跑出汇报的结果。

**Comment by PungTeng** [comment]
> 你好，那个训练迭代时间实际不需要那么长，我们设置的稍微长一些是为了更容易跑出汇报的结果。

非常感谢作者休息时间对我问题回答！

**Comment by wymanCV** [comment]
感谢您对我们工作的关注，如果有后续问题欢迎重新打开issue，或者通过电子邮件联络我。
