### ISSUE TITLE
Hi ， Can you share the BDD100K dataset link and it's coco style annotation?

### ISSUE THREAD

**Issue by ga546** [CityU-AIM-Group/SIGMA#24]

**Comment by wymanCV** [comment]
Hi, sorry for the late reply.

Kindly check out the updated BDD100k link in the newly committed README.md.

**Comment by ga546** [comment]
> Hi @ga546 , sorry for the late reply.
> 
> Kindly check out the updated BDD100k link in the newly pushed README.md. Thanks.

Thank you very much
