### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by SATURN2021** [CityU-AIM-Group/SIGMA#25]
作者您好！我在训练后出现如下报错：
![image](https://user-images.githubusercontent.com/92077510/208056476-db024aba-23e9-4955-88ec-b56bd43b97a6.png)
这个报错会不会影响模型训练和测试的效果？如果影响的话，应该如何解决？
期待您的回复！

**Comment by wymanCV** [comment]
您好，请问您是跑的哪一个DA设定，有没有修改某些地方？ 我刚才尝试了一下训练，没有遇到您这个报错。

**Comment by SATURN2021** [comment]
您好！我跑的是Sim10k_to_Cityscapes，运行命令如下：
<img width="794" alt="6124ebfac707cf2ba722dd071490864" src="https://user-images.githubusercontent.com/92077510/208104515-b43d3269-6e6f-45ba-b999-19ac111cc7db.png">

**Comment by wymanCV** [comment]
您好， 我刚才试了下也是没有遇到您的问题，我是直接clone的最新版本代码然后跑的。要不您试一下其他设定，比如city2foogy，排查下是不是因为数据的问题，或者重新clone一下代码？

![image](https://user-images.githubusercontent.com/93365573/208111781-d1892e0c-5478-4e1b-b930-a423a7a5d6c3.png)
![image](https://user-images.githubusercontent.com/93365573/208111226-2601f2de-2d6d-4cb3-bd99-f0912d627529.png)

**Comment by SATURN2021** [comment]
感谢作者的回复！我仔细研究了一下train_net_da.py的代码，发现我这边inference()函数少输入了一个cfg参数，改正之后报错解决。

**Comment by wymanCV** [comment]
好的, 感谢您对我们工作的关注.
如果有后续问题欢迎重新开启iusse,或者通过邮件与我交流.
