### ISSUE TITLE
训练被killed

### ISSUE THREAD

**Issue by SATURN2021** [CityU-AIM-Group/SIGMA#26]
作者您好！我在训练时设置了3万次迭代，但是在22600次迭代之后程序被killed：
<img width="891" alt="22ecb38643d6689564b81de3fff165a" src="https://user-images.githubusercontent.com/92077510/208289596-3b29c781-9e71-46f7-a6e0-143346088728.png">
我的设备为V100-SXM2-32GB，
CPU：12核 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz，内存:43GB
batchsize为4.
想问一下killed是不是内存的问题，该如何解决？

**Comment by wymanCV** [comment]
您好，不太确定是不是机器的原因，不过加载最近模型继续训练就好。

**Comment by SATURN2021** [comment]
谢谢作者的回复！我看experiments里面保存的都是最好的模型结果，如果像您说的那样继续训练的话，是从得到最好的结果那次迭代继续训练，还是从被killed那次迭代继续训练呢？
举个例子，我设置训练迭代次数3万，在2万次被killed，此时保存的最好结果是在15000次迭代时产生的。这个时候我加载这个最好的模型结果继续训练，最大迭代次数MAX_ITER设为15000还是10000？
期待您的解答！

**Comment by wymanCV** [comment]
您好，按照您这个情况，继续训练15000迭代就可以的。

另外其实MAX_ITER的设置相对来说比较弹性，每个DAOD的方法使用的迭代次数通常都不相同，您也可以尝试多训练一些迭代以达到相对更稳定的结果。

**Comment by SATURN2021** [comment]
明白啦！感谢作者的回复！

**Comment by wymanCV** [comment]
感谢您对我们工作的关注.
如果有后续问题欢迎重新开启iusse,或者通过邮件与我交流.
