### ISSUE TITLE
question about node hallucination

### ISSUE THREAD

**Issue by michaelku1** [CityU-AIM-Group/SIGMA#28]

**Comment by wymanCV** [comment]
Hi, thanks for your attention. The code for the mentioned part is at [here](https://github.com/CityU-AIM-Group/SIGMA/blob/main/fcos_core/modeling/rpn/fcos/graph_matching_head.py). Do you need some help?

**Comment by michaelku1** [comment]
Hi, I originally had a question specifically about node halluciation from the paper, but I just figured it out. Will close this issue for now, Thanks.
