### ISSUE TITLE
Question about number of warm up iterations

### ISSUE THREAD

**Issue by michaelku1** [CityU-AIM-Group/SIGMA#29]
Hi, I would like to ask you about the number of iters used for warm-up. Haven't run the code myself but I was wondering if the 2000 iters is where the global-align only model converged? Did you find that number out of experimentation or did you follow the original config setting from previous works? Thanks.

**Comment by wymanCV** [comment]
Hi, sorry for the confusion. The published configs are for end-to-end training without a two-stage warm-up (global alignment) for easier reproducibility. As discussed in our supplementary materials, our method can achieve similar results in this end-to-end manner. 

The mentioned warm-up iterations are only from the base object detector training, which doesn't have any influence on DAOD.
