### ISSUE TITLE
Hello,  I faced another issue when i tried to start training process. can you please take a look?

### ISSUE THREAD

**Issue by AstuWeb** [CityU-AIM-Group/SIGMA#3]
![train](https://user-images.githubusercontent.com/50729468/166727910-87c5a05b-94b4-4023-9395-39b7a8acccd7.png)

**Comment by wymanCV** [comment]
It seems that you still utilize the wrong annotation files, PLS download  [this](https://github.com/CityU-AIM-Group/SIGMA/issues/2), and don't change anything other than the "DATA_DIR " in paths_catalog.py, 

Especially for this: 
![image](https://user-images.githubusercontent.com/93365573/166852680-68cce7bf-ddbd-4c8e-bf78-1562e552bbf4.png)

I think you still use your only annotations, which is not the same as ours.

**Comment by wymanCV** [comment]
Hi, have you fixed this problem? I cloned the project again and trained the model, but didn't face such an issue..

**Comment by AstuWeb** [comment]
Apologies for the delay I was working on another problem . I am using the same annotation file you gave me and I followed the procedure from the updated readme. I don't think that I change paths_catalog.py file. but for the time being the cuda on my computer  stopped  working so I have to completely remove and install it again. After that I will try again following all your suggestions. so for now I am closing the issue and I'll be back if it will not work. Thank you again.
