### ISSUE TITLE
运行时报段错误Segmentation fault

### ISSUE THREAD

**Issue by ck6698000** [CityU-AIM-Group/SIGMA#30]
代码运行至加载完预训练权重后报错，一开始没有traceback，使用详细报错命令后有了这样的信息。

Current thread 0x00007f1a5f1c6700 (most recent call first):
  File "<frozen importlib._bootstrap\>", line 372 in \__init\__
  File "<frozen importlib._bootstrap_external\>", line 606 in spec_from_file_location
  File "/gs/home/rswang/proj/SIGMA/fcos_core/utils/imports.py", line 12 in import_file
  File "/gs/home/rswang/proj/SIGMA/fcos_core/data/build.py", line 221 in make_data_loader_source
  File "tools/train_net_da.py", line 559 in train
  File "tools/train_net_da.py", line 717 in main
  File "tools/train_net_da.py", line 728 in <module>
/var/spool/slurm/job8041367/slurm_script: line 23: 96067 Segmentation fault      (core dumped) python tools/train_net_da.py --config-file configs/sigma_plus_plus/mine.yaml

编译用的gcc5.3没看到有报错，代码自带的环境检测如下：
Cuda compilation tools, release 10.2, V10.2.89
CUDA used to build PyTorch: 10.1
CUDA runtime version: 10.2.89

不知道是哪里出了问题呢？请作者指点一二~~

ps: cudatoolkit==10.1 torch1.4.0

**Comment by wymanCV** [comment]
您好，感谢您对我们工作的关注！

据我所知，“Segmentation fault (core dumped)” 应该是这个框架[maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark)比较常见的报错（我们是基于这个框架部署的算法），所以相应有挺多issus提供解决方案，比如这个[issue](https://github.com/facebookresearch/maskrcnn-benchmark/issues/857) 和这个[issue](https://github.com/facebookresearch/maskrcnn-benchmark/issues/50)，通过您给的信息我推测还是编译问题，您可以尝试下这些解决策略。谢谢~

**Comment by ck6698000** [comment]
> 您好，感谢您对我们工作的关注！
> 
> 据我所知，“Segmentation fault (core dumped)” 应该是这个框架[maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark)比较常见的报错（我们是基于这个框架部署的算法），所以相应有挺多issus提供解决方案，比如这个[issue](https://github.com/facebookresearch/maskrcnn-benchmark/issues/857) 和这个[issue](https://github.com/facebookresearch/maskrcnn-benchmark/issues/50)，通过您给的信息我推测还是编译问题，您可以尝试下这些解决策略。谢谢~

好的 谢谢速度的回复~我再排查排查问题
