### ISSUE TITLE
ImportError: cannot import name '_C' from 'fcos_core' (/SIGMA/sigma++/SIGMA/fcos_core/__init__.py)

### ISSUE THREAD

**Issue by M-o-magic** [CityU-AIM-Group/SIGMA#38]
您好，我遵循教程的步骤，到了训练的时候，进行教程中命令行进行训练是没有问题的。但如果使用pycharm自带的训练功能（绿色三角），在配置好参数后进行训练，是会报以上错的。请问有什么办法可以解决吗？

**Comment by wymanCV** [comment]
您好,感谢对我们工作的关注.
1. 据我所知,直接使用pycharm可能会出现相对路径错误,无法导入一些通过相对路径导入的包,因为这个IDE会默认项目主目录. 目前看/SIGMA/sigma++/SIGMA/fcos_core/__init__.py这个路径好像是不太对的.
2. 您可以在检查下是否正确clone SIGMA++的branch, 而不是main branch.

**Comment by llk0123** [comment]
请问后续解决这个问题了吗，我也是显示
ImportError: cannot import name '_C' from 'fcos_core' (/Home/llk/project/SIGMA/SIGMA-main/fcos_core/__init__.py)
但是我未能找到正确的路径
