### ISSUE TITLE
Compare with model EPM？

### ISSUE THREAD

**Issue by sunshehai** [CityU-AIM-Group/SIGMA#39]
@wymanCV 
Thank you for your contribution. If I want to compare with model EPM, I noticed that model EPM needs two steps of training, while yours only needs one step. If possible, may I ask how to change your model to be like EPM? Thank you for your reply.

**Comment by sunshehai** [comment]
@wymanCV 
May I ask about the comparative experiment with model EPM in your paper? Is the model used in the original EPM paper or modified? Thank you. If it is modified, could you please provide the modified EPM?

**Comment by wymanCV** [comment]
Hi, as claimed in the implementation details, the pre-trained stage in our previous experiments removes BGM by disabling the following two items.

WITH_DOMAIN_INTERACTION False
MATCHING_CFG 'none'

We also tried to use EPM's 1st stage model, finding that using it can achieve similar final results.
