### ISSUE TITLE
source-only 训练，低mAP

### ISSUE THREAD

**Issue by M-o-magic** [CityU-AIM-Group/SIGMA#47]
我在使用sigma代码时，想先用source-only预训练下试试看，所以把DA_ON关闭了。但是在source-only训练过程中，发现训练到40的mAP后,模型损失不再下降。我尝试过调整batch_size和learning_rate，但mAP就是上不去。当我使用yolov5进行sourceonly数据集的训练时，是可以到96的mAP的。
您对此问题有想法吗？

**Comment by wymanCV** [comment]
您好，谢谢对我们工作的关注．

您可以尝试下用官方[FCOS代码](https://github.com/tianzhi0549/FCOS)试一下，其中trianing schedule与DA情况下不太一样．

另外请问您是使用自己的数据集吗？我们之前实验发现FCOS在某些其他数据集，比如Pascal VOC上的稳定性确实比Faster RCNN差一些，参数设置不好和其他检测器相比会出现比较大的性能差距．
