### ISSUE TITLE
in the middle of training process at iteration 2100 it show this error

### ISSUE THREAD

**Issue by asuweb0** [CityU-AIM-Group/SIGMA#5]
![reduc](https://user-images.githubusercontent.com/50729468/167318755-cf7281de-a142-445c-844c-4f59c8c15194.PNG)

**Comment by wymanCV** [comment]
Is this from Vgg16 backbone? and do you change batch size?

**Comment by astuweb** [comment]
yes it throws ÇUDA OUT OF MEMORY error so that i changed the batch size to 1

**Comment by astuweb** [comment]
the backbone is R-50-FPN-RETINANET''

**Comment by wymanCV** [comment]
> yes it throws ÇUDA OUT OF MEMORY error so I changed the batch size to 1

Since the cross-image graph propagation (within batch) is necessary, batch size should be set to at least 2. We tested batch size 2 and 4. Do you change the learning rate for bs=1?

**Comment by astuweb** [comment]
I didn't change the learning rate but it still throws cuda out of memory error using batch size of 2

**Comment by wymanCV** [comment]
> I didn't change the learning rate but it still throws cuda out of memory error using batch size of 2

We used 2080 Ti (12GB) for bs=2 and V100 (36GB) for bs=4, and never havd a try for bs=1.

It is common practice to halve the learning rate if you halve the batch size. For now, you can try to halve the learning rate. We will further test the bs=1 if you still face such a problem. But we still don't recommend training with only bs=1.

**Comment by astuweb** [comment]
at the beginning it starts well but then at some pint of the iteration it show that error. I will try reducing the learning rate.

**Comment by astuweb** [comment]
'CUDA out of memory' even for learning rate of 0.0005

**Comment by wymanCV** [comment]
> 'CUDA out of memory' even for learning rate of 0.0005

It seems that your GPU memory is too small., 

Try to further reduce the number of sampled nodes by changing this in the YAML config file. (The number of sampled nodes could increase during the training.)

NUM_NODES_PER_LVL_SR:  50
NUM_NODES_PER_LVL_TG:  50

**Comment by astuweb** [comment]
this is the gpu I am using. so can i reduce NUM_NODES_PER_LVL_SR and  NUM_NODES_PER_LVL_TG to any number?
![NV](https://user-images.githubusercontent.com/50729468/167324111-0064b673-a588-4866-8078-cff0c9cdefb3.PNG)

**Comment by wymanCV** [comment]
> this is the gpu I am using. so can i reduce NUM_NODES_PER_LVL_SR and NUM_NODES_PER_LVL_TG to any number? ![NV](https://user-images.githubusercontent.com/50729468/167324111-0064b673-a588-4866-8078-cff0c9cdefb3.PNG)

Actually, 8GP GPU is a little bit small for the detection tasks. 
Sure, you can try any number of the node number. But you'd better not reduce too much, since we have shown an analysis in Table 4.

**Comment by astuweb** [comment]
Okay and isn't there a checkpoint because it starts from the scratch every time i restarted it even though  it did many iterations before

**Comment by wymanCV** [comment]
> Okay and isn't there a checkpoint because it starts from the scratch every time i restarted it even though it did many iterations before

We automatically start to save the checkpoint if the validation results are larger than SOLVER.INITIAL_AP50 to save the desk space. You can change SOLVER.INITIAL_AP50 to 0 to save more checkpoints.

**Comment by astuweb** [comment]
let me try it by  applying your suggestions this issue will be open until the process finishes

**Comment by astuweb** [comment]
thank you I will re-open when an issue is encountered.

**Comment by wymanCV** [comment]
Hi, I have reproduced your issue, and this issue should have been addressed in the latest commit.

Since your bs is too small (bs=1), there exists an extreme case in which there are only two nodes in the source domain and no nodes in the target domain. Then, SIGMA will split the source nodes into two parts to train the matching branch, leading to the wrong size of target nodes [256] instead of [num_node, 256].
 
![image](https://user-images.githubusercontent.com/93365573/167363418-f5fdbcb4-8e2a-4e91-be8d-1d45f71568c6.png)

We fix this bug by adding these lines, which directly jump out the middle head if there are not enough source nodes.

![image](https://user-images.githubusercontent.com/93365573/167365991-689cdc49-8ffd-43ca-8e06-54349a6d25bf.png)

**Comment by wymanCV** [comment]
> thank you I will re-open when an issue is encountered.

We have updated README about the small batch-size training for your convenience. ResNet 50 backbone always gives better results than VGG 16.

**Comment by astuweb** [comment]
oh sorry for the late  replay i see I'll check out the updates made. but  now regarding the check point after more than 24 hours of training unfortunately there was a power interruptions and when  i start the training it starts from the scratch and also it shows the same estimated remaining time as the original one even though it saved checkpoint each steps. here is the screenshot of it and also i showed the saved models in the GIF file. please kindly check it out.
![chckpt](https://user-images.githubusercontent.com/50729468/167629140-5e867f40-b17a-477d-b073-85806c79e1a8.png)
![chckpt (1)](https://user-images.githubusercontent.com/50729468/167629160-f5869403-340a-4091-a767-f98745552933.png)
![TEST](https://user-images.githubusercontent.com/50729468/167629176-3934a7b9-e16a-45d4-8ce4-4c95d5e6b0bd.gif)

**Comment by wymanCV** [comment]
Hi, that's okay since the framework will automatically load the latest checkpoint. You can directly ignore the INFO message since it is from EPM, which isn't used in our project.  You can directly continue to train the model and set the warm-up iterations to 0. It seems to work properly now, if you face the previous issue again, you only need to add those lines mentioned above.

I recommend you to try changing the learning rate back to 0.0025 to train faster as I find your model converges too slowly with only bs=1.  As the updated readme, you need to train double iterations if you halve the batch size.  Usually, for bs=2 of resnet 50 (0.0025 lr), it can achieve 40+ mAP only using 10000 iterations.

**Comment by astuweb** [comment]
Noted with thanks so I think I don't have t redownload the repo the update is on file  'graph_matching_head.py'  just changing the learning rate to 0.0025 and batch size 2  so I can just replace graph_matching_head.py right?

**Comment by astuweb** [comment]
Okay it's clear let me give it a try another thing is that using the VGG pretrained model for evaluation throws  'Runtime Error: size mismatch'  error

**Comment by astuweb** [comment]
but i checked it before updating the annotation file probably because of the wrong annotation file I will check it again with the updated annotation after finishing the current process

**Comment by asuweb0** [comment]
Dear sir the ''çuda out of memory' problem still persists after ten thousands of iterations even though I applied the recommendation provided So i updated it to the original. is there any other recommendation please?

**Comment by wymanCV** [comment]
> Dear sir the ''çuda out of memory' problem still persists after ten thousands of iterations even though I applied the recommendation provided So i updated it to the original. is there any other recommendation please?
Hi, maybe you can disable the one-to-one (o2o) matching by setting MODEL.MIDDLE_HEAD.GM.MATCHING_CFG 'none'，which will save some CUDA memory.

**Comment by tysnow2022** [comment]
Okay thank you for the updates.

**Comment by asuweb0** [comment]
Ok Thanks I will try it.
