### ISSUE TITLE
Missing annotation files for Pascal Voc based settings

### ISSUE THREAD

**Issue by GingerCohle** [CityU-AIM-Group/SIGMA#50]
Thank you for your excellent work. I encounter a problem. I dont have split annotation file da_transferred_train in yaml file. pls help
![image](https://github.com/CityU-AIM-Group/SIGMA/assets/37873318/8831eed1-9542-4cf4-95eb-c63aa4aa77c1)

**Comment by GingerCohle** [comment]
![image](https://github.com/CityU-AIM-Group/SIGMA/assets/37873318/ad6a7e78-b078-422b-9945-898902854c65)

**Comment by wymanCV** [comment]
@GingerCohle 

Hi, thank you so much for pointing out this mistake.

I just uploaded these files on Onedrive [link](https://portland-my.sharepoint.com/:u:/g/personal/wuyangli2-c_my_cityu_edu_hk/EbgU4dq5URhOtMYtliFH5W0BxDQT3-fdBhiQ08v4ObGHfw?e=fHoUny). You need to put them into corresponding folders following the VOC format. Please have a check, thanks.

**Comment by GingerCohle** [comment]
WoW, thats amazing! Again thanks you for your consistent support for your excellent work.
