### ISSUE TITLE
T-SNE可视化

### ISSUE THREAD

**Issue by Wang-Y-B** [CityU-AIM-Group/SIGMA#54]
我看到您在论文最终实验部分汇报了T-SNE的可视化分析，虽然您在论文中已经描述了这一部分的计算过程，但我仍没有很好地理解这一部分，请问您是否可以提供相关的代码，感谢

**Comment by wymanCV** [comment]
感谢对于我们工作的关注！
可以参考这个issue：
https://github.com/CityU-AIM-Group/SIGMA/issues/46#issuecomment-1609564802
