### ISSUE TITLE
准确率和召回率的计算有接口吗

### ISSUE THREAD

**Issue by M-o-magic** [CityU-AIM-Group/SIGMA#56]

**Comment by wymanCV** [comment]
Hi, thanks for your interest.  The used coco-style evaluation has the APIs for recall and precision, as shown in [pycocotools](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py).

You can use the generated json prediction file and GT json to evaluate with pycocotools. Besides, you can also modify the coco_eval.py here, which may be a little bit complicated.
https://github.com/CityU-AIM-Group/SIGMA/blob/d8265ac8ec0e74ef84298f25cae532d4fe67302e/fcos_core/data/datasets/evaluation/coco/coco_eval.py#L52
