### ISSUE TITLE
A problem when running ‘python setup.py build develop’.

### ISSUE THREAD

**Issue by Lybnn** [CityU-AIM-Group/SIGMA#57]
The following problem occurs when I run ‘python setup.py build develop’:
g++: error: /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cpu/ROIAlign_cpu.o: No such file or directory
g++: error: /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cpu/nms_cpu.o: No such file or directory
error: command '/usr/bin/g++' failed with exit code 1
But inside the cuda folder, ROIAlign_cuda.o, ROIPool_cuda.o, nms.o, ml_nms.o, and SigmoidFocalLoss_cuda.o are generated
The complete log is shown below:
running build
running build_py
running egg_info
writing fcos.egg-info/PKG-INFO
writing dependency_links to fcos.egg-info/dependency_links.txt
writing requirements to fcos.egg-info/requires.txt
writing top-level names to fcos.egg-info/top_level.txt
reading manifest file 'fcos.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'fcos/configs'
adding license file 'LICENSE'
writing manifest file 'fcos.egg-info/SOURCES.txt'
/home/ubuntu/anaconda3/envs/SIGMA/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'fcos.bin' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'fcos.bin' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'fcos.bin' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'fcos.bin' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/home/ubuntu/anaconda3/envs/SIGMA/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'fcos_core.csrc' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'fcos_core.csrc' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'fcos_core.csrc' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'fcos_core.csrc' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/home/ubuntu/anaconda3/envs/SIGMA/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'fcos_core.csrc.cpu' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'fcos_core.csrc.cpu' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'fcos_core.csrc.cpu' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'fcos_core.csrc.cpu' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
/home/ubuntu/anaconda3/envs/SIGMA/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'fcos_core.csrc.cuda' as data is deprecated, please list it in `packages`.
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'fcos_core.csrc.cuda' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'fcos_core.csrc.cuda' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'fcos_core.csrc.cuda' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

!!

  check.warn(importable)
copying fcos_core/csrc/cpu/ROIAlign_cpu.cpp -> build/lib.linux-x86_64-cpython-37/fcos_core/csrc/cpu
copying fcos_core/csrc/cpu/nms_cpu.cpp -> build/lib.linux-x86_64-cpython-37/fcos_core/csrc/cpu
running build_ext
/home/ubuntu/anaconda3/envs/SIGMA/lib/python3.7/site-packages/torch/utils/cpp_extension.py:782: UserWarning: The detected CUDA version (11.3) has a minor version mismatch with the version that was used to compile PyTorch (11.1). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'fcos_core._C' extension
Emitting ninja build file /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.11.1.git.kitware.jobserver-1
g++ -pthread -B /home/ubuntu/anaconda3/envs/SIGMA/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/ubuntu/anaconda3/envs/SIGMA/compiler_compat -L/home/ubuntu/anaconda3/envs/SIGMA/lib -Wl,-rpath=/home/ubuntu/anaconda3/envs/SIGMA/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cpu/ROIAlign_cpu.o /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cpu/nms_cpu.o /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cuda/ROIAlign_cuda.o /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cuda/ROIPool_cuda.o /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cuda/SigmoidFocalLoss_cuda.o /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cuda/ml_nms.o /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cuda/nms.o /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/vision.o -L/home/ubuntu/anaconda3/envs/SIGMA/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-cpython-37/fcos_core/_C.cpython-37m-x86_64-linux-gnu.so
g++: error: /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cpu/ROIAlign_cpu.o: No such file or directory
g++: error: /media/ubuntu/9a32be42-b1fc-4942-91da-4a28a2388ede/zyb/SIGMA/build/temp.linux-x86_64-cpython-37/fcos_core/csrc/cpu/nms_cpu.o: No such file or directory
error: command '/usr/bin/g++' failed with exit code 1
This is my configuration environment：
# packages in environment at /home/ubuntu/anaconda3/envs/SIGMA:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
ca-certificates           2024.3.11            h06a4308_0    defaults
certifi                   2022.12.7        py37h06a4308_0    defaults
cycler                    0.11.0                   pypi_0    pypi
cython                    3.0.10                   pypi_0    pypi
decorator                 5.1.1              pyhd3eb1b0_0    defaults
fonttools                 4.38.0                   pypi_0    pypi
imageio                   2.31.2                   pypi_0    pypi
ipython                   7.31.1           py37h06a4308_1    defaults
jedi                      0.18.1           py37h06a4308_1    defaults
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.4                h6a678d5_1    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.6            py37h06a4308_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.11.1.1                 pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0    defaults
packaging                 24.0                     pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1           py37h06a4308_0    defaults
prompt-toolkit            3.0.36           py37h06a4308_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pycocotools               2.0                      pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.7.16               h7a1cb2a_0    defaults
python-dateutil           2.9.0.post0              pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.6.0                    pypi_0    pypi
setuptools                65.6.3           py37h06a4308_0    defaults
six                       1.16.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0    defaults
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.14               h39e8969_0    defaults
torch                     1.10.0+cu111             pypi_0    pypi
torchaudio                0.10.0+rocm4.1           pypi_0    pypi
torchvision               0.11.0+cu111             pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.7.1            py37h06a4308_0    defaults
typing-extensions         4.7.1                    pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
wheel                     0.38.4           py37h06a4308_0    defaults
xz                        5.4.6                h5eee18b_1    defaults
yacs                      0.1.8                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_1    defaults
How should I solve this problem, please?Thanks！

**Comment by wymanCV** [comment]
Thanks for your interest.

It seems to be related to your gcc version. Can you check whether gcc >= 4.9?

**Comment by Lybnn** [comment]
Yes, my version is 5.5.0.But I don't understand why this problem occurs
