### ISSUE TITLE
Can I use Faster RCNN as a backbone Detector?

### ISSUE THREAD

**Issue by tysnow2022** [CityU-AIM-Group/SIGMA#6]

**Comment by wymanCV** [comment]
Sure! SIGMA works on the image-level feature and doesn't depend on specific detection heads, meaning that it can be extended to different detection algorithms, even for segmentation tasks. We had tried a quick (naive) implementation on the famous DAFRCNN (IJCV) framework and found it can still work. We may provide a Faster RCNN based implementation in our extended journal version. But for now, I think that you have to try it by yourself. 

Actually, this framework contains an unfinished Faster RCNN implementation, and I hope to unify it with DAFRCNN (IJCV) in the future if time is available.
