### ISSUE TITLE
Hello! I encountered the following error. Could you give me some suggestions?

### ISSUE THREAD

**Issue by modeny** [CityU-AIM-Group/SIGMA#9]
I configured the environment as required by INSTALL.md and my environment is torch=1.4.1,torchvision=0.2.1,cudatoolkit=10.1.
The error is as follows
![QQ截图20220609201744](https://user-images.githubusercontent.com/66890425/172844956-2a27ce30-5596-4e5c-8f8e-6f0b6b0bd0a8.png)

**Comment by wymanCV** [comment]
> This is my GCC version. ![图片](https://user-images.githubusercontent.com/66890425/172849577-c3568b41-7e0f-4860-b6f5-0933e00ee7e2.png)

Hi, the GCC version seems okay. I just had a quick search and found this [issue](https://github.com/sfzhang15/ATSS/issues/14)., which is the same as yours. Maybe you can follow his tips by rebuilding it. Make sure your cudatoolkit environment is correctly loaded (sometimes, you need to use "module load" to load cuda on the server)

**Comment by wymanCV** [comment]
Hi, have you fixed this problem? 

You can send me your compiling (building) logs, which will be helpful for me in finding the solution for you.

**Comment by wymanCV** [comment]
Hi, I'm sorry that I didn't find problems in your compiling logs.

Could you check your local cuda runtime version on your computer (not the conda environment)? I found this similar [issue](https://github.com/facebookresearch/detectron2/issues/62), which seems to be helpful.

**Comment by modeny** [comment]
Thanks a lot! I checked my nvcc version, and found it is 10.0. So I change the version of cudatoolkit to 10.0 and rebuild. Finally, the error is gone.

**Comment by wymanCV** [comment]
You're welcome, and I will then close this issue. You can reopen it if you have further problems.

**Comment by modeny** [comment]
I trained about 50000 iters using 2080Ti with batch size as 2, and I found that the evaluation results are quite unstable. The AP50 fluctuated around 41 and reach a maximum of 43.5. I wanna ask you how to judge the convergence of the model and select the results to report. 
Thanks a lot.
